version: '3.9'

services:
  backend:
    image: abakar98/jenkins-api
    pull_policy: always
    container_name: backend  
    env_file:
      - /var/www/.env
    ports:
      - "3001:3001"  # ← CHANGÉ : backend sur 3001
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: abakar98/jenkins-frontend
    pull_policy: always
    container_name: frontend
    env_file:
      - /var/www/.env  # ← AJOUTÉ : pour que le frontend ait accès aux variables
    ports:
      - "80:3000"  # ← CHANGÉ : frontend Next.js tourne sur 3000 dans le container
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge