version: '3.9'

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-prod
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    image: abakar98/jenkins-api:latest
    container_name: backend
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=http://46.105.54.141
    expose:
      - "3001"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: abakar98/jenkins-frontend:latest
    container_name: frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKENDURL=http://46.105.54.141
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge