services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-prod
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

  backend:
    image: abakar98/jenkins-api:latest
    container_name: backend
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3001
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=https://2clock-mar-8.fr
    expose:
      - "3001"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: abakar98/jenkins-frontend:latest
    container_name: frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKENDURL=https://2clock-mar-8.fr/api
    expose:
      - "3000"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network: